### ISSUE TITLE
User error with connect()

### ISSUE THREAD

**Issue by JaneSullivan-NOAA** [afsc-assessments/afscdata#12]
When I run
```
akfin <- connect(db = "akfin")
```
I get the following error:
```
Error: nanodbc/nanodbc.cpp:1118: IM002: [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified
```

When I change the `connect()` source code from:
```
    DBI::dbConnect ( odbc::odbc(),
                     driver = db,
                     uid = user,
                     pwd = pwd )
```
to
```
    DBI::dbConnect ( odbc::odbc(),
                     db,
                     uid = user,
                     pwd = pwd )
```
the error goes away, and I'm able to connect to the database without issues.

Is this machine specific? If so is there a set up test we can run within the function to help users troubleshoot this issue?

**Comment by BenWilliams-NOAA** [comment]
i ran into the same issue today (thinking something updated). same result here so i removed the `driver =` and works fine now.
