### ISSUE TITLE
add cols

### ISSUE THREAD

**Issue by pete-hulson** [afsc-assessments/afscdata#28]
https://github.com/afsc-assessments/afscdata/blob/369dec607b45f1f762e04d509f465b30d9af8c5f/R/queries.R#L597
i think adding haul_join and port_join should be part of the base output rather than adding them as fields, will need these for age/length expansion - also, not have them is causing an error in afscassess when running fish_age_comp

**Comment by BenWilliams-NOAA** [comment]
there is an `add_fields` input - can add any columns you want. or do you want to change the base level columns included?

**Comment by pete-hulson** [comment]
i saw that add_fields part, but, i think this function would become more generalizable if we added port and haul joins to the base level columns - to steve's comment on the other issue, if we need any other trip/haul identifiers other than these then we can add those in the add_fields part. to the rockfish case - we'll be changing up how the fishery age/length comps are expended for all the other goa stocks in the next full assessments and will need these fields (or, at least, i would suggest we do)

**Comment by BenWilliams-NOAA** [comment]
should be addressed via the `q_fsh_obs` function
