### ISSUE TITLE
remove this line

### ISSUE THREAD

**Issue by pete-hulson** [afsc-assessments/afscdata#31]
https://github.com/afsc-assessments/afscdata/blob/fe8678c170a7196f8871cc71bf8de7a65baf9440/R/queries.R#L4433
here take out year>=(yr-3) & year<=(yr-1), so that we grab all the data (and don't forget to add haul_join and port_join as columns to get rid of that other issue

**Comment by BenWilliams-NOAA** [comment]
kinda making more sense to me to just make a `q_hauls` function, add haul and port join to the specimen and length data and everything else is done as a 2nd function. thoughts?

**Comment by pete-hulson** [comment]
you could do that, but i think you may need to add a trip id of some sort to the observer catch/age/length that then is an identifier to subsequently join the hauls and port joins by... seems more efficient just to add the haul and port join columns here than to add a trip id column here and add a separate function to add columns
