### ISSUE TITLE
doesn't match

### ISSUE THREAD

**Issue by pete-hulson** [afsc-assessments/afscdata#37]
https://github.com/afsc-assessments/afscdata/blob/b36ad961f895d55187889cf810fc5efcef74feb4/R/queries.R#L287
this table doesn't match the goa.agecomp_total, which is what we've always pulled from, can we switch this table to agecomp_total with paste0(region, '.AGECOMP_TOTAL'), would also need to change the sizecomp one to paste0(region, '.SIZECOMP_TOTAL')

**Comment by BenWilliams-NOAA** [comment]
See #2 in appendix B
https://docs.google.com/document/d/1ie0it6G_V_PrpO1fYe-731Fvubuahn2yi0ixBIpaYO8/edit

gap_products is where everything is moving to. possibly best to make the leap sooner rather than later?

**Comment by pete-hulson** [comment]
sounds good to me
