### ISSUE TITLE
revisit naming amak

### ISSUE THREAD

**Issue by BenWilliams-NOAA** [afsc-assessments/afscdata#44]
https://github.com/afsc-assessments/afscdata/blob/2ef4e210f20f4e1d4db5bc2148c7fe2289826029/R/atka_mackerel.R#L13

@JaneSullivan-NOAA there is also a GOA mackerel assessment. I suggest either making this code more flexible (region switch) or creating a amak.R script that has bsai_amak.R and goa_amak.R in it (probably most similar to the general structure). 
Not a priority (i.e. post-assessments!), just some background organization/structure items.
Let me know if you have a better structure idea, just winging it here!

**Comment by JaneSullivan-NOAA** [comment]
Makes sense! Will work with the GOA author (Sandra?) after assessment season.

**Comment by jimianelli** [comment]
GOA Atkas long been a Tier 6 species (nobody refers to them as "mackerels") but spose their recent 400% increase could warrant special treatment (probably connected to BSAI stock...)

**Comment by BenWilliams-NOAA** [comment]
Thanks both of  you - Jane shuffled the file structure and I added in a catch and trawl biomass query for `goa_amak`
