### ISSUE TITLE
Same as previous, lowercase area/ region name when saving file

### ISSUE THREAD

**Issue by KristenOmori-NOAA** [afsc-assessments/afscdata#52]
https://github.com/afsc-assessments/afscdata/blob/3f41c2c1b714b1f3ad4bde019c0f18c743cce5d5/R/queries.R#L121

Same as with the bts length data... to make the raw data query compatible with the afscasssess, can you make the file output area name to lowercase?

**Comment by BenWilliams-NOAA** [comment]
i'll adjust, but should all work if enter the area as lowercase to start with

**Comment by KristenOmori-NOAA** [comment]
Actually, can you change to goa_bts_length_specimen_data.csv

**Comment by KristenOmori-NOAA** [comment]
the area name gets changed to upper case in the "global" section of that function.

**Comment by BenWilliams-NOAA** [comment]
nah it changes to ` ar = toupper(area)`

**Comment by BenWilliams-NOAA** [comment]
> Actually, can you change to goa_bts_length_specimen_data.csv

I'm gonna recommend against this - mostly for historical reasons. The specimen data has always been associated with age information/samples so combining these would increase the likelihood of downstream confusion

**Comment by KristenOmori-NOAA** [comment]
That's fine, would you be able to change the file name to match what goes into the afscassess::bts_length_comp data file then?

**Comment by BenWilliams-NOAA** [comment]
pretty sure this was fixed?

**Comment by KristenOmori-NOAA** [comment]
yeah... the query outputs are all linked to the appropriate data formatting functions.
